import { CAMPUSES, getMeetingPointById } from '@/constants/campuses';
export const CAMPUS_LOCATIONS = CAMPUSES.map((campus) => campus.name);
const getMeetingPointLabel = (id) => { var _a, _b; return (_b = (_a = getMeetingPointById(id)) === null || _a === void 0 ? void 0 : _a.name) !== null && _b !== void 0 ? _b : 'Punto de encuentro'; };
export const RECOMMENDED_TRIPS = [
    {
        id: 't1',
        driverId: 'u1',
        driverName: 'Constanza Vidal',
        dest: 'Providencia',
        meetPoint: getMeetingPointLabel('mp-uai-pen-entradaprin'),
        price: 2500,
        seats: 2,
        departAt: '2024-10-31T07:45:00-03:00',
        routeNotes: 'Ruta rápida por Vespucio Sur',
        originCampusId: 'uai-penalolen',
        destinationCampusId: 'uandes-san-carlos',
        meetingPointId: 'mp-uai-pen-entradaprin',
    },
    {
        id: 't2',
        driverId: 'u2',
        driverName: 'Ignacio López',
        dest: 'Plaza Ñuñoa',
        meetPoint: getMeetingPointLabel('mp-uai-pen-biblioteca'),
        price: 2200,
        seats: 3,
        departAt: '2024-10-31T09:00:00-03:00',
        routeNotes: 'Acepta bicicletas plegables',
        originCampusId: 'uai-penalolen',
        destinationCampusId: 'udd-las-condes',
        meetingPointId: 'mp-uai-pen-biblioteca',
    },
    {
        id: 't3',
        driverId: 'u3',
        driverName: 'María Abarca',
        dest: 'La Reina',
        meetPoint: getMeetingPointLabel('mp-uai-pen-estacionamientos'),
        price: 2000,
        seats: 1,
        departAt: '2024-10-31T18:15:00-03:00',
        routeNotes: 'Hace parada en Tobalaba',
        originCampusId: 'uai-penalolen',
        destinationCampusId: 'uai-vina-del-mar',
        meetingPointId: 'mp-uai-pen-estacionamientos',
    },
];
export const DRIVER_SPOTLIGHT = [
    {
        id: 'u1',
        name: 'Constanza Vidal',
        email: 'constanza@alumnos.uai.cl',
        role: 'driver',
        rating: 4.9,
        car: 'Mazda 3 2021',
        completedTrips: 182,
        expertise: ['Ruta costa', 'Viajes express'],
    },
    {
        id: 'u2',
        name: 'Ignacio López',
        email: 'ignacio@alumnos.uai.cl',
        role: 'driver',
        rating: 4.8,
        car: 'Hyundai Tucson 2019',
        completedTrips: 154,
        expertise: ['Equipaje extra', 'Mascotas'],
    },
];
export const UPCOMING_TRIP = {
    id: 't4',
    driverId: 'u4',
    driverName: 'Francisca Ortega',
    dest: 'Barrio Italia',
    meetPoint: getMeetingPointLabel('mp-uai-pen-biblioteca'),
    price: 2300,
    seats: 4,
    departAt: '2024-10-31T20:00:00-03:00',
    routeNotes: 'Incluye parada en Irarrázaval',
    originCampusId: 'uai-penalolen',
    destinationCampusId: 'uandes-san-carlos',
    meetingPointId: 'mp-uai-pen-biblioteca',
};
export const PASSENGER_MANIFEST = [
    {
        id: 'p1',
        name: 'Jorge Rivera',
        faculty: 'Ingeniería Comercial',
        pickup: 'Estacionamiento sur',
        seat: '2A',
        status: 'confirmado',
        badges: ['Pago verificado'],
    },
    {
        id: 'p2',
        name: 'Lucía Prado',
        faculty: 'Diseño',
        pickup: 'Entrada gimnasio',
        seat: '2B',
        status: 'pendiente',
        badges: ['Primera vez'],
    },
    {
        id: 'p3',
        name: 'Sebastián Valdés',
        faculty: 'Derecho',
        pickup: 'Metro Grecia',
        seat: '3A',
        status: 'completado',
        badges: ['5★ historial'],
    },
];
export const BOOKINGS_SUMMARY = [
    {
        id: 'b1',
        title: 'Peñalolén → Providencia',
        driverName: 'Constanza Vidal',
        date: 'Hoy, 07:45',
        seats: 1,
        status: 'confirmado',
    },
    {
        id: 'b2',
        title: 'San Carlos → Ñuñoa',
        driverName: 'Ignacio López',
        date: 'Hoy, 09:00',
        seats: 2,
        status: 'pendiente',
    },
    {
        id: 'b3',
        title: 'Viña → Valparaíso',
        driverName: 'María Abarca',
        date: 'Mañana, 18:15',
        seats: 1,
        status: 'completado',
    },
];
export const TRIP_TIMELINE = [
    {
        id: 'tt1',
        title: 'Encuentro',
        detail: 'Ingreso principal Campus Peñalolén',
        time: '18:10',
    },
    {
        id: 'tt2',
        title: 'Ruta intermedia',
        detail: 'Parada coordinada en Metro Tobalaba',
        time: '18:40',
    },
    {
        id: 'tt3',
        title: 'Destino final',
        detail: 'Barrio Italia, Av. Italia con Santa Isabel',
        time: '19:15',
    },
];
